### ISSUE TITLE
Junction example fails

### ISSUE THREAD

**Issue by mcilrain** [juntalis/ntfslink-python#8]
Windows 7 Ultimate 64-bit

```
>>> from ntfslink import junctions
>>> junctions.example()
Junction Example
Temporarily created C:\Temp folder for the purpose of this example.
create(/Temp, temp)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ntfslink\junctions.py", line 116, in example
    print 'create(%s, %s)' % (sfolder, sjunction), create(sfolder, sjunction)
  File "ntfslink\junctions.py", line 59, in create
    result = create_reparse_point(srcpath, linkpath, _prefill)
  File "ntfslink\common.py", line 81, in create_reparse_point
    pReparseInfo = prefill(reparseInfo, source, substlink, link_name, isabs)
  File "ntfslink\junctions.py", line 32, in _prefill
    (bufflen, reparseInfo.ReparseDataLength) = CalculateLength(MountPointBuffer, reparseInfo.MountPoint)
  File "ntfslink\internals\__init__.py", line 98, in CalculateLength
    if pathBuffer.PrintNameOffset == 0 else \
AttributeError: 'MountPointBuffer' object has no attribute 'PrintNameOffset'
```

**Comment by 1nv** [comment]
Open internals/_winioctl.py and replace the following code (line 200:
`	_fields_ = [

		# See SymbolicLinkBuffer.PathBuffer for our reasoning.
		('PathBuffer', WCHAR * MAX_REPARSE_PATH_BUFFER)
	]`
with this one:
`	_fields_ = [
		('SubstituteNameOffset', USHORT),
		('SubstituteNameLength', USHORT),
		('PrintNameOffset', USHORT),
		('PrintNameLength', USHORT),
		# See SymbolicLinkBuffer.PathBuffer for our reasoning.
		('PathBuffer', WCHAR * MAX_REPARSE_PATH_BUFFER)
	]`

**Comment by juntalis** [comment]
Not sure how I missed this mistake or how I didn't see the issue. Should be fixed now - will test when I get home.
